cmake_minimum_required(VERSION 3.21)
project(scrollproto LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(Qt6 REQUIRED COMPONENTS Gui Qml Quick WebEngineQuick)
qt_standard_project_setup()
qt_add_executable(scrollproto main.cpp)
target_compile_definitions(scrollproto PRIVATE SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(scrollproto PRIVATE Qt6::Gui Qt6::Qml Qt6::Quick Qt6::WebEngineQuick)
