#!/usr/bin/env python3
"""Render the website's per-theme assets: palettes, wallpapers, favicons, shots.

The website draws the browser in one palette at a time and lets the reader
switch. Everything that palette touches is generated here, from the Omarchy
theme's own `colors.toml`, so a chrome change or an upstream palette change is
a re-run rather than a photo session and a round of eyedropping.

Per theme it writes:

- `website/themes.css` -- one `body[data-theme]` block, holding the palette
  roles Omaweb itself resolved rather than an approximation of them. A theme
  file names a handful of colours; Omaweb derives every role it draws from
  them and floors the quiet ones against the ground they sit on, so the roles
  are read back out of the browser through `omaweb-ui-lab --dump-palette`.
- `website/assets/icons/favicon-<theme>.svg`, the application icon in the
  theme's own ground and foreground, and `wordmark-<theme>.svg`, the wordmark
  in its foreground. The default theme's favicon is also written to
  `website/favicon.svg`, which is where a browser asks for it.
- `website/assets/shots/<theme>/<state>.png`, one capture per interface state,
  composited over a wallpaper generated from the same palette.

The wallpaper is the design `.desk__wall` and `.desk__grain` already draw in
`website/styles.css` -- three radial glows over a diagonal gradient, under a
field of diagonal stripes -- so the still shots and the page's own live mock
sit on one wallpaper rather than on two. One geometry, colours only.

## Headless, and no pointer

Nothing here needs a compositor, a pointer or a screen grab:

    QT_QPA_PLATFORM=offscreen QT_QUICK_BACKEND=software \\
      ./build/dev/omaweb-ui-lab --tabs --show settings:tabs --capture out.png

`OMAWEB_THEME_FILE` points the lab at a rendered theme without installing it,
and `OMAWEB_NO_OMARCHY_TEMPLATE` stops the run writing into the reader's own
Omarchy configuration. The capture keeps real alpha -- the chrome comes out at
its theme's opacity -- which is what makes compositing over a wallpaper give
what a desktop shows rather than a flat approximation of it.

## The page in the shots is the Start page

`omaweb-ui-lab` runs no engine, so where a webpage would be it draws the Start
page. Every state captured here is therefore real chrome: a Space with a day's
worth of tabs and a new tab on show, two sections of Settings, History, and the
window with its sidebar hidden. A shot with a real page in it needs the browser
on a live compositor and `grim`, which gives up every property above and means
whoever runs it is capturing their own screen. If the site ever wants one hero
shot with a page in it, take that one by hand, once: it is the exception, and
this is why.

## Running it

    scripts/build_website_themes.py --lab ./build/dev/omaweb-ui-lab

Only the standard library is used, so there is nothing to install. Themes are
read from `/usr/share/omarchy/themes` and `~/.config/omarchy/themes`, the user
directory winning; a theme that is installed in neither is skipped with a word
about it. Nothing is written outside this repository.

The images are deliberately not gated in CI. Rendering differs across machines
and fonts, and a flaky gate on a picture is worse than a stale picture.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import pathlib
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import tomllib
import zlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "integrations" / "omarchy" / "omaweb.json.tpl"
APPLICATION_ICON = ROOT / "assets" / "icons" / "omaweb.svg"
WORDMARK = ROOT / "website" / "assets" / "icons" / "omaweb.svg"
GENERATED = "<!-- Generated by scripts/build_website_themes.py. Do not edit. -->"
WEBSITE = ROOT / "website"
SHOTS = WEBSITE / "assets" / "shots"
ICONS = WEBSITE / "assets" / "icons"
STYLESHEET = WEBSITE / "themes.css"

THEME_DIRECTORIES = [
    pathlib.Path.home() / ".config" / "omarchy" / "themes",
    pathlib.Path("/usr/share/omarchy/themes"),
]

# The themes the site offers, in the order it offers them. The first is the
# default: the one the page comes up in and the one its favicon is.
THEMES = [
    ("oligarchy", "Oligarchy"),
    ("tokyo-night", "Tokyo Night"),
    ("catppuccin", "Catppuccin"),
    ("nord", "Nord"),
    ("everforest", "Everforest"),
    ("gruvbox", "Gruvbox"),
]

# The interface states worth a picture, and the lab arguments that reach each.
# `--tabs` seeds every one of them: a Space at rest draws neither the Pinned
# section nor the tab list, and the vertical strip with Pinned tabs above it is
# what distinguishes this browser at a glance.
STATES = [
    ("space", ["--tabs"]),
    ("settings", ["--tabs", "--show", "settings:tabs"]),
    ("blocking", ["--tabs", "--show", "settings:content-blocking"]),
    ("history", ["--tabs", "--show", "history"]),
    ("collapsed", ["--tabs", "--show", "collapsed"]),
]

# Two states the lab can reach and this deliberately does not ship. Site
# information is about the page on show and the lab has no page, so it draws
# the panel saying so. `--private` paints the private palette, which is the
# theme's own ground with its private accent cast over it: a difference the
# browser is right to keep quiet and a screenshot cannot carry, and the shot
# comes out as the ordinary window with its Pinned section missing. Both are
# one argument away for anyone who wants to look.

# The palette roles the website spends, taken from the palette Omaweb resolved.
# The opaque grounds rather than the translucent ones: CSS composites the
# translucency itself, from `--sidebar-alpha`.
RESOLVED_ROLES = {
    "--bg": "windowOpaque",
    "--sidebar": "sidebarOpaque",
    "--fg": "text",
    "--accent": "accent",
    "--urgent": "urgent",
}

# And the roles the page takes from the theme's own name for them instead.
# Omaweb floors quiet text for contrast against every ground it draws it on,
# one of which is a hover fill the template spends the theme's own `muted` on;
# a theme whose `muted` is a mid-grey pushes that floor to near-white, which is
# the right answer for a browser drawing text on six grounds and the wrong one
# for a page with a single ground, where it would read brighter than the
# foreground it is meant to be quieter than.
NAMED_ROLES = {"--muted": "mutedText"}

# The desktop the window is shown standing on, as a fraction of the capture.
# Enough of it for the wallpaper to be a wallpaper rather than a border.
MARGIN = 0.1


# ------------------------------------------------------------------ themes


def theme_colors(name: str) -> dict[str, str] | None:
    """The theme's own `colors.toml`, or None where it is not installed."""
    for directory in THEME_DIRECTORIES:
        colors = directory / name / "colors.toml"
        if colors.is_file():
            with colors.open("rb") as handle:
                return {
                    key: value
                    for key, value in tomllib.load(handle).items()
                    if isinstance(value, str)
                }
    return None


def render_theme_file(colors: dict[str, str], target: pathlib.Path) -> dict:
    """Substitute the shipped Omarchy template against one theme's palette.

    Omarchy renders this itself at theme-switch time, into its own state
    directory. A screenshot run cannot switch the reader's desktop six times,
    so it renders the same template here instead.

    `{{ font_family }}` is the one token Omarchy leaves standing: it is not a
    `colors.toml` key, and the palette's family list falls through to the next
    name. This drops the token for the same reason, so the browser resolves the
    same family a desktop gives it.
    """
    rendered = TEMPLATE.read_text(encoding="utf-8")
    for key, value in colors.items():
        rendered = rendered.replace("{{ %s }}" % key, value)
    rendered = rendered.replace('"{{ font_family }}", ', "")
    remaining = re.findall(r"\{\{[^}]*\}\}", rendered)
    if remaining:
        raise SystemExit(f"the template names colours this theme does not: {remaining}")
    target.write_text(rendered, encoding="utf-8")
    return json.loads(rendered)


def resolved_palette(lab: pathlib.Path, theme_file: pathlib.Path) -> dict:
    """The palette Omaweb draws, read back out of the browser itself."""
    with tempfile.TemporaryDirectory() as scratch:
        dump = pathlib.Path(scratch) / "palette.json"
        run_lab(lab, theme_file, ["--dump-palette", str(dump), "--validate-qml"])
        return json.loads(dump.read_text(encoding="utf-8"))


def run_lab(lab: pathlib.Path, theme_file: pathlib.Path, arguments: list[str]) -> None:
    environment = dict(os.environ)
    environment.update(
        {
            "OMAWEB_THEME_FILE": str(theme_file),
            # Without this, following the Omarchy theme writes a template into
            # the reader's own configuration directory.
            "OMAWEB_NO_OMARCHY_TEMPLATE": "1",
            "QT_QPA_PLATFORM": "offscreen",
            "QT_QUICK_BACKEND": "software",
        }
    )
    result = subprocess.run(
        [str(lab), *arguments], env=environment, capture_output=True, text=True
    )
    if result.returncode != 0:
        sys.exit(f"{lab.name} {' '.join(arguments)} failed:\n{result.stderr}")


# --------------------------------------------------------------- colours


def channels(color: str) -> tuple[int, int, int]:
    """`#rrggbb` or Qt's `#aarrggbb`, as opaque RGB."""
    digits = color.lstrip("#")
    if len(digits) == 8:
        digits = digits[2:]
    if len(digits) != 6:
        raise SystemExit(f"not a colour this script can read: {color}")
    return tuple(int(digits[index : index + 2], 16) for index in (0, 2, 4))


def hex_color(color: str) -> str:
    red, green, blue = channels(color)
    return f"#{red:02x}{green:02x}{blue:02x}"


# ------------------------------------------------------------------- png


def read_png(path: pathlib.Path) -> tuple[int, int, bytearray]:
    """Width, height and RGBA bytes of an 8-bit non-interlaced PNG.

    Written out rather than taken from a library because this script has no
    dependencies to install: the captures are what Qt writes, which is 8-bit
    RGBA, and the wallpapers are what this script writes.
    """
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit(f"{path} is not a PNG")
    width = height = depth = kind = 0
    compressed = bytearray()
    offset = 8
    while offset < len(data):
        (length,) = struct.unpack_from(">I", data, offset)
        name = data[offset + 4 : offset + 8]
        body = data[offset + 8 : offset + 8 + length]
        offset += 12 + length
        if name == b"IHDR":
            width, height, depth, kind, _, _, interlace = struct.unpack(">IIBBBBB", body)
            if depth != 8 or kind not in (2, 6) or interlace != 0:
                raise SystemExit(f"{path} is not an 8-bit non-interlaced RGB(A) PNG")
        elif name == b"IDAT":
            compressed += body
        elif name == b"IEND":
            break

    source = zlib.decompress(bytes(compressed))
    stride = width * (4 if kind == 6 else 3)
    step = 4 if kind == 6 else 3
    pixels = bytearray(width * height * 4)
    previous = bytearray(stride)
    at = 0
    for row in range(height):
        filter_kind = source[at]
        line = bytearray(source[at + 1 : at + 1 + stride])
        at += 1 + stride
        unfilter(filter_kind, line, previous, step)
        if kind == 6:
            pixels[row * width * 4 : (row + 1) * width * 4] = line
        else:
            base = row * width * 4
            for column in range(width):
                pixels[base + column * 4 : base + column * 4 + 3] = line[
                    column * 3 : column * 3 + 3
                ]
                pixels[base + column * 4 + 3] = 255
        previous = line
    return width, height, pixels


def unfilter(kind: int, line: bytearray, previous: bytearray, step: int) -> None:
    """PNG's five per-scanline filters, undone in place."""
    if kind == 0:
        return
    if kind == 1:
        for index in range(step, len(line)):
            line[index] = (line[index] + line[index - step]) & 0xFF
    elif kind == 2:
        for index in range(len(line)):
            line[index] = (line[index] + previous[index]) & 0xFF
    elif kind == 3:
        for index in range(len(line)):
            left = line[index - step] if index >= step else 0
            line[index] = (line[index] + ((left + previous[index]) >> 1)) & 0xFF
    elif kind == 4:
        for index in range(len(line)):
            left = line[index - step] if index >= step else 0
            up = previous[index]
            corner = previous[index - step] if index >= step else 0
            estimate = left + up - corner
            if abs(estimate - left) <= abs(estimate - up) and abs(estimate - left) <= abs(
                estimate - corner
            ):
                nearest = left
            elif abs(estimate - up) <= abs(estimate - corner):
                nearest = up
            else:
                nearest = corner
            line[index] = (line[index] + nearest) & 0xFF
    else:
        raise SystemExit(f"unknown PNG filter {kind}")


def write_png(path: pathlib.Path, width: int, height: int, pixels: bytes) -> None:
    """Write RGB bytes as an 8-bit PNG. Wallpapers and composites are opaque."""
    raw = bytearray()
    stride = width * 3
    for row in range(height):
        raw.append(0)
        raw += pixels[row * stride : (row + 1) * stride]

    def chunk(name: bytes, body: bytes) -> bytes:
        return (
            struct.pack(">I", len(body))
            + name
            + body
            + struct.pack(">I", zlib.crc32(name + body) & 0xFFFFFFFF)
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )


# ------------------------------------------------------------- wallpaper


def wallpaper(palette: dict, width: int, height: int) -> bytearray:
    """The design `.desk__wall` and `.desk__grain` draw, in this palette.

    Kept a transcription of the stylesheet rather than a second design: the
    page shows the live mock on the CSS version of this and the shots on this
    one, and two wallpapers under one interface would read as two products.
    Each glow is an ellipse in fractions of the canvas, painted over a diagonal
    gradient, with a field of diagonal stripes over the lot.
    """
    background = channels(palette["windowOpaque"])
    foreground = channels(palette["text"])
    accent = channels(palette["accent"])
    urgent = channels(palette["urgent"])

    # linear-gradient(152deg, color-mix(bg 34%, #000), bg). CSS measures the
    # angle clockwise from "to top", and the gradient line is long enough that
    # the far corners still reach the last stop.
    radians = math.radians(152)
    along = (math.sin(radians), -math.cos(radians))
    span = abs(width * along[0]) + abs(height * along[1])
    start = tuple(round(value * 0.34) for value in background)

    # radial-gradient(rx ry at cx cy, colour alpha stop, ...) for each glow,
    # painted in the order CSS composites them: last listed is furthest back.
    glows = [
        (0.20, 0.18, 0.62, 0.14, foreground, [(0.0, 0.52), (0.70, 0.0)]),
        (0.26, 0.24, 0.82, 0.72, urgent, [(0.0, 0.82), (0.44, 0.34), (0.68, 0.0)]),
        (0.34, 0.30, 0.24, 0.34, accent, [(0.0, 0.95), (0.40, 0.46), (0.66, 0.0)]),
    ]
    prepared = []
    for fraction_x, fraction_y, at_x, at_y, color, stops in glows:
        centre_x, centre_y = at_x * width, at_y * height
        radius_x, radius_y = fraction_x * width, fraction_y * height
        # The x term of the ellipse distance is the same down every column.
        columns = [((column + 0.5 - centre_x) / radius_x) ** 2 for column in range(width)]
        prepared.append((columns, centre_y, radius_y, color, stops))

    # repeating-linear-gradient(58deg, transparent 0 30px, mix(fg 13%) 30px 60px)
    grain_radians = math.radians(58)
    grain = (math.sin(grain_radians), -math.cos(grain_radians))

    pixels = bytearray(width * height * 3)
    at = 0
    for row in range(height):
        y = row + 0.5
        base_projection = y * along[1]
        base_grain = y * grain[1]
        rows = [
            (columns, ((y - centre_y) / radius_y) ** 2, color, stops)
            for columns, centre_y, radius_y, color, stops in prepared
        ]
        for column in range(width):
            x = column + 0.5
            # The diagonal ground.
            position = (x * along[0] + base_projection) / span + 0.5
            position = 0.0 if position < 0.0 else (1.0 if position > 1.0 else position)
            red = start[0] + (background[0] - start[0]) * position
            green = start[1] + (background[1] - start[1]) * position
            blue = start[2] + (background[2] - start[2]) * position

            for columns, row_term, color, stops in rows:
                distance = math.sqrt(columns[column] + row_term)
                if distance >= stops[-1][0]:
                    continue
                alpha = stop_alpha(distance, stops)
                if alpha <= 0.0:
                    continue
                red += (color[0] - red) * alpha
                green += (color[1] - green) * alpha
                blue += (color[2] - blue) * alpha

            if ((x * grain[0] + base_grain) % 60.0) >= 30.0:
                red += (foreground[0] - red) * 0.13
                green += (foreground[1] - green) * 0.13
                blue += (foreground[2] - blue) * 0.13

            pixels[at] = clamp(red)
            pixels[at + 1] = clamp(green)
            pixels[at + 2] = clamp(blue)
            at += 3
    return pixels


def stop_alpha(distance: float, stops: list[tuple[float, float]]) -> float:
    """The alpha a CSS gradient's stop list gives one point on its ray."""
    if distance <= stops[0][0]:
        return stops[0][1]
    for (first_at, first), (second_at, second) in zip(stops, stops[1:]):
        if distance <= second_at:
            reach = second_at - first_at
            if reach <= 0.0:
                return second
            return first + (second - first) * (distance - first_at) / reach
    return stops[-1][1]


def clamp(value: float) -> int:
    return 0 if value < 0 else (255 if value > 255 else int(value + 0.5))


def blur(pixels: bytearray, width: int, height: int, radius: int) -> bytearray:
    """A separable box blur, twice, which is close enough to a gaussian.

    Off unless asked for. A blur under the translucent surfaces is what a
    compositor with `decoration:blur` on would show, and Omarchy ships that
    off; there is no client-side blur for the browser to ask through either, so
    a sharp desktop is what a stock install actually looks like. The site's own
    live mock blurs its sidebar with `backdrop-filter`, which is the page's
    licence rather than the desktop's.
    """
    for _ in range(2):
        pixels = box_pass(pixels, width, height, radius)
        pixels = transpose(pixels, width, height)
        pixels = box_pass(pixels, height, width, radius)
        pixels = transpose(pixels, height, width)
    return pixels


def box_pass(pixels: bytearray, width: int, height: int, radius: int) -> bytearray:
    out = bytearray(len(pixels))
    window = radius * 2 + 1
    for row in range(height):
        base = row * width * 3
        for channel in range(3):
            line = pixels[base + channel : base + width * 3 : 3]
            total = line[0] * radius + sum(line[: radius + 1])
            for column in range(width):
                out[base + column * 3 + channel] = total // window
                leaving = line[max(column - radius, 0)]
                entering = line[min(column + radius + 1, width - 1)]
                total += entering - leaving
    return out


def transpose(pixels: bytearray, width: int, height: int) -> bytearray:
    out = bytearray(len(pixels))
    for row in range(height):
        source = row * width * 3
        for column in range(width):
            target = (column * height + row) * 3
            out[target : target + 3] = pixels[source + column * 3 : source + column * 3 + 3]
    return out


# ------------------------------------------------------------- composite


def composite(
    capture: pathlib.Path, ground: bytearray, canvas: tuple[int, int], offset: tuple[int, int]
) -> bytearray:
    """The window's own pixels over the desktop, at the alpha it was captured at.

    The capture keeps the opacity the theme gave each surface, so the desktop
    shows through the sidebar and the empty page ground exactly as far as a
    compositor would let it.
    """
    width, height = canvas
    left, top = offset
    shot_width, shot_height, shot = read_png(capture)
    pixels = bytearray(ground)
    for row in range(shot_height):
        target = ((top + row) * width + left) * 3
        source = row * shot_width * 4
        for column in range(shot_width):
            alpha = shot[source + 3]
            if alpha == 0:
                target += 3
                source += 4
                continue
            if alpha == 255:
                pixels[target : target + 3] = shot[source : source + 3]
            else:
                for channel in range(3):
                    over = shot[source + channel]
                    under = pixels[target + channel]
                    pixels[target + channel] = (over * alpha + under * (255 - alpha)) // 255
            target += 3
            source += 4
    return pixels


# ------------------------------------------------------------------ assets


def favicon(palette: dict) -> str:
    """The application icon in one theme's ground and foreground.

    The two colours are replaced by the literals the shipped icon draws them
    with, so a redesign that renames them fails here instead of quietly
    shipping six copies of one palette.
    """
    source = APPLICATION_ICON.read_text(encoding="utf-8")
    ground, mark = "#1a1b26", "#c0caf5"
    for color in (ground, mark):
        if color not in source:
            raise SystemExit(f"{APPLICATION_ICON} no longer draws {color}")
    return stamp(
        source.replace(ground, hex_color(palette["windowOpaque"])).replace(
            mark, hex_color(palette["text"])
        )
    )


def wordmark(palette: dict) -> str:
    """The wordmark in one theme's foreground, on the page's own ground.

    Drawn black by the editor that made it, and the lettering carries no fill
    of its own, so the colour is set once on the root and the mark's own black
    is turned into an inheritance. The page used to invert the whole image to
    get white out of it, which no theme could reach.
    """
    source = WORDMARK.read_text(encoding="utf-8")
    black = "fill:#000000"
    if black not in source:
        raise SystemExit(f"{WORDMARK} no longer draws its mark in {black}")
    source = source.replace(black, "fill:inherit", 1)
    opened = source.index("<svg") + len("<svg")
    color = hex_color(palette["text"])
    return stamp(source[:opened] + f'\n   fill="{color}"' + source[opened:])


def stamp(svg: str) -> str:
    """Mark the file generated, after any XML declaration rather than before.

    A comment ahead of `<?xml ...?>` is not well-formed, and the wordmark was
    saved by an editor that writes one.
    """
    end = svg.find("?>")
    at = 0 if end < 0 else svg.index("\n", end) + 1
    return svg[:at] + GENERATED + "\n" + svg[at:]


def stylesheet(palettes: dict[str, tuple[dict, dict]]) -> str:
    lines = [
        "/* Generated by scripts/build_website_themes.py. Do not edit.",
        " *",
        " * The roles Omaweb resolved from each theme's own colors.toml, not an",
        " * approximation of them: the browser derives every role it draws from the",
        " * handful of colours a theme names, and floors the quiet ones against the",
        " * ground they sit on. Re-run the script to pick up an upstream change.",
        " */",
        "",
    ]
    for name, _ in THEMES:
        if name not in palettes:
            continue
        palette, named = palettes[name]
        lines.append(f'body[data-theme="{name}"] {{')
        for token, role in RESOLVED_ROLES.items():
            lines.append(f"  {token}: {hex_color(palette[role])};")
        for token, role in NAMED_ROLES.items():
            lines.append(f"  {token}: {hex_color(named[role])};")
        # The sidebar's translucency is the theme's, as it is in the browser.
        alpha = palette.get("opacity", {}).get("sidebar", 0.95)
        lines.append(f"  --sidebar-alpha: {round(alpha * 100)}%;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


# -------------------------------------------------------------------- main


def build(
    theme: str, lab: pathlib.Path, scratch: pathlib.Path, blurred: bool
) -> tuple[dict, dict] | None:
    colors = theme_colors(theme)
    if colors is None:
        print(f"  {theme}: not installed, skipped")
        return None

    theme_file = scratch / f"{theme}.json"
    named = render_theme_file(colors, theme_file)
    palette = resolved_palette(lab, theme_file)

    (ICONS / f"favicon-{theme}.svg").write_text(favicon(palette), encoding="utf-8")
    (ICONS / f"wordmark-{theme}.svg").write_text(wordmark(palette), encoding="utf-8")

    captures = {}
    for state, arguments in STATES:
        target = scratch / f"{theme}-{state}.png"
        run_lab(lab, theme_file, [*arguments, "--capture", str(target)])
        captures[state] = target

    width, height, _ = read_png(captures["space"])
    margin = round(width * MARGIN)
    canvas = (width + margin * 2, height + margin * 2)
    ground = wallpaper(palette, *canvas)
    if blurred:
        ground = blur(ground, *canvas, radius=max(2, round(canvas[0] / 90)))

    for state, capture in captures.items():
        pixels = composite(capture, ground, canvas, (margin, margin))
        write_png(SHOTS / theme / f"{state}.png", *canvas, pixels)
        print(f"  {theme}/{state}.png")
    return palette, named


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--lab",
        type=pathlib.Path,
        default=ROOT / "build" / "dev" / "omaweb-ui-lab",
        help="the omaweb-ui-lab binary to capture with",
    )
    parser.add_argument(
        "--theme", action="append", help="build only this theme; repeatable"
    )
    parser.add_argument(
        "--blur",
        action="store_true",
        help="blur the desktop behind the window, as a compositor with blur on would",
    )
    arguments = parser.parse_args()

    if not arguments.lab.is_file():
        return fail(f"no lab at {arguments.lab}; build the dev or ui preset first")
    if not any(directory.is_dir() for directory in THEME_DIRECTORIES):
        print("No Omarchy themes on this machine; nothing to build.")
        return 0

    wanted = [entry for entry in THEMES if not arguments.theme or entry[0] in arguments.theme]
    if not wanted:
        return fail(f"no such theme: {', '.join(arguments.theme)}")

    palettes = {}
    with tempfile.TemporaryDirectory() as directory:
        scratch = pathlib.Path(directory)
        for theme, _ in wanted:
            print(f"{theme}:")
            built = build(theme, arguments.lab, scratch, arguments.blur)
            if built is not None:
                palettes[theme] = built

    if not palettes:
        return fail("none of the requested themes are installed")

    STYLESHEET.write_text(stylesheet(palettes), encoding="utf-8")
    print(f"  {STYLESHEET.relative_to(ROOT)}")

    default = THEMES[0][0]
    if default in palettes:
        shutil.copyfile(ICONS / f"favicon-{default}.svg", WEBSITE / "favicon.svg")
        print(f"  {(WEBSITE / 'favicon.svg').relative_to(ROOT)}")
    return 0


def fail(message: str) -> int:
    print(message, file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
