#!/usr/bin/env bash
#
# Writes the PKGBUILD for `omaweb`, the binary package the pacman repository
# serves, from `packaging/PKGBUILD`, which builds `omaweb-git`.
#
# The two packages differ in four lines and agree on everything else: the same
# dependencies, the same release preset, the same inventory, the same install
# notice. Keeping a second PKGBUILD in the tree would mean every dependency
# added to one and forgotten in the other ships a package that does not run, and
# nothing would report the disagreement. Deriving one from the other makes them
# unable to disagree.
#
# What changes, and why:
#
#   pkgname    `-git` names a package pacman expects to be rebuilt from source.
#              A binary repository serves `omaweb`.
#   pkgver     A VCS package computes its version in `pkgver()` from a checkout
#              the reader of a binary package does not have. The tag is the
#              version here, the same tag CMake reads (ADR 0028).
#   conflicts  Each package conflicts with the other, so a reader who built from
#              source is asked before the repository replaces it.
#   source     The commit the tag names, rather than a branch.
#
# Every substitution is checked against the file it was made in, so a rename or
# a reordering upstream fails here rather than silently producing a package that
# is missing the change.
#
#     scripts/make_release_pkgbuild.sh --version 0.5.0 --output <dir> \
#         [--source-url <url>]
#
# The output directory receives the PKGBUILD and the install file it names,
# which is what `makepkg` reads: it takes both from the directory it runs in
# rather than from the repository.

set -euo pipefail

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
version=""
output=""
source_url=""

usage() {
    echo "usage: $0 --version <x.y.z> --output <dir> [--source-url <url>]" >&2
    exit 2
}

while (( $# > 0 )); do
    case "$1" in
        --version) version="${2:-}"; shift 2 ;;
        --output) output="${2:-}"; shift 2 ;;
        --source-url) source_url="${2:-}"; shift 2 ;;
        *) usage ;;
    esac
done

[[ -n "$version" && -n "$output" ]] || usage

# pacman compares versions itself and a dash separates `pkgver` from `pkgrel`,
# so a version carrying one is not a version it can read. The tag's leading `v`
# is accepted and dropped, because the caller usually has the tag rather than
# the number.
version="${version#v}"
if [[ ! "$version" =~ ^[0-9]+(\.[0-9]+)*([a-z0-9._]*)$ ]]; then
    echo "make_release_pkgbuild: '$version' is not a version pacman can read" >&2
    exit 2
fi

# The published package builds the commit the tag names. A caller with its own
# checkout to build from says so; the default is the public repository, which is
# what a reader reproducing the build would use.
if [[ -z "$source_url" ]]; then
    source_url="\$_pkgname::git+https://github.com/villekivela/omaweb.git#tag=v${version}"
fi

pkgbuild="$repo_root/packaging/PKGBUILD"
install_file="$repo_root/packaging/omaweb-git.install"
for required in "$pkgbuild" "$install_file"; do
    [[ -f "$required" ]] || { echo "make_release_pkgbuild: no $required" >&2; exit 1; }
done

mkdir -p "$output"
generated="$output/PKGBUILD"

# Each edit is applied on its own and then checked, rather than run as one
# script whose failures cancel out.
replace() {
    local what="$1" pattern="$2" replacement="$3" file="$4"
    if ! grep -qE "$pattern" "$file"; then
        echo "make_release_pkgbuild: packaging/PKGBUILD has no $what line to rewrite" >&2
        echo "make_release_pkgbuild: expected a line matching $pattern" >&2
        exit 1
    fi
    # `|` as the delimiter, because a replacement can carry a URL.
    sed -i -E "s|$pattern|$replacement|" "$file"
}

remove() {
    local what="$1" pattern="$2" file="$3"
    if ! grep -qE "$pattern" "$file"; then
        echo "make_release_pkgbuild: packaging/PKGBUILD has no $what line to remove" >&2
        echo "make_release_pkgbuild: expected a line matching $pattern" >&2
        exit 1
    fi
    sed -i -E "\|$pattern|d" "$file"
}

{
    cat <<'HEADER'
# Generated by scripts/make_release_pkgbuild.sh from packaging/PKGBUILD. Do not
# edit: a change made here is lost the next time a release is built. Change
# packaging/PKGBUILD, which both packages are built from, or the script that
# derives this one.
#
# This is the binary package the [omaweb] pacman repository serves. Its source
# twin, omaweb-git, stays in the repository for `makepkg -si` from a checkout.
HEADER
    echo
    cat "$pkgbuild"
} > "$generated"

replace "pkgname" '^pkgname=omaweb-git$' 'pkgname=omaweb' "$generated"
replace "pkgver" '^pkgver=.+$' "pkgver=${version}" "$generated"
replace "source" '^source=\(.+\)$' "source=(\"${source_url}\")" "$generated"

# `provides` and `conflicts` are written in terms of `$_pkgname` upstream, which
# is this package's own name here. A package that provides and conflicts with
# itself is not what either line is for: what a binary package has to say is
# that it replaces the source one.
replace "provides" '^provides=\(.+\)$' "conflicts=('omaweb-git')" "$generated"
remove "conflicts" '^conflicts=\("\$_pkgname"\)$' "$generated"

# The version is the tag, so the function that computed one from a checkout has
# nothing left to do. Left in, it would run `git describe` in the source tree and
# overwrite the version this package is named for.
if ! grep -q '^pkgver() {$' "$generated"; then
    echo "make_release_pkgbuild: packaging/PKGBUILD has no pkgver() to remove" >&2
    exit 1
fi
sed -i '/^pkgver() {$/,/^}$/d' "$generated"
# The blank line that separated it from the next function is now one of a pair.
# `packaging/PKGBUILD` has no double blank line of its own, so squeezing them is
# the removal finishing rather than a reformatting of the file.
squeezed=$(cat -s "$generated")
printf '%s\n' "$squeezed" > "$generated"
if grep -q 'pkgver()' "$generated"; then
    echo "make_release_pkgbuild: pkgver() survived removal" >&2
    exit 1
fi

# `install="$pkgname.install"` now names omaweb.install, so the file travels
# under the name the generated PKGBUILD asks for.
cp "$install_file" "$output/omaweb.install"

echo "make_release_pkgbuild: wrote $generated for omaweb $version"
