#!/usr/bin/env python3
"""Vendor uBlock Origin's resource library into third_party/ubo-scriptlets.

Two sets are copied byte for byte from a pinned uBO commit: the scriptlets a
`##+js(...)` rule can name, and the web-accessible resources a `$redirect`
rule can substitute for a request. Nothing under the vendored tree is edited.
`scriptlets.json` and `redirects.json` beside them are the same sets expressed
as adblock-rust resource descriptors, generated by
scripts/build_ubo_scriptlets.mjs and scripts/build_ubo_redirects.mjs and
committed so that a build needs neither Node nor the network. The manifest
pins both kinds: the copies by their upstream blob, the generated files by
their digest.

Usage:

    scripts/sync_ubo_scriptlets.py --verify           # local tree matches the manifest
    scripts/sync_ubo_scriptlets.py --check-upstream   # what changed since the pin
    scripts/sync_ubo_scriptlets.py --sync             # re-fetch the pinned commit
    scripts/sync_ubo_scriptlets.py --sync --ref 1.69.0
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import subprocess
import sys
import tarfile
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPOSITORY = "gorhill/uBlock"
BRANCH = "master"

# Every module under src/js/resources registers itself, so the whole directory
# is the scriptlet library. src/web_accessible_resources is the substitute
# bodies, and redirect-resources.js beside it is the list of which of them a
# filter may name — the directory also holds uBO's own extension pages, which
# that list leaves out and the generator therefore never emits.
#
# Vendored path -> the suffix a file in it must carry, or None for all of them.
VENDORED_DIRECTORIES = {
    "src/js/resources": ".js",
    "src/web_accessible_resources": None,
}

# Files the modules import from outside those directories, plus upstream's
# license. Vendored at their upstream paths so the relative imports resolve.
VENDORED_FILES = (
    "LICENSE.txt",
    "src/js/arglist-parser.js",
    "src/js/jsonpath.js",
    "src/js/redirect-resources.js",
    "src/js/urlskip.js",
)

VENDOR_ROOT = Path(__file__).resolve().parent.parent / "third_party" / "ubo-scriptlets"
MANIFEST_PATH = VENDOR_ROOT / "MANIFEST.json"
# Generated file -> the script that builds it from the copies beside it.
GENERATORS = {
    "scriptlets.json": "build_ubo_scriptlets.mjs",
    "redirects.json": "build_ubo_redirects.mjs",
}
SCRIPT_ROOT = Path(__file__).resolve().parent

API = "https://api.github.com"
CODELOAD = "https://codeload.github.com"


def token() -> str | None:
    """GitHub's unauthenticated API allowance is 60 calls an hour. Reuse
    whatever token is already on the machine."""
    for name in ("GITHUB_TOKEN", "GH_TOKEN"):
        value = os.environ.get(name)
        if value:
            return value
    try:
        result = subprocess.run(["gh", "auth", "token"], capture_output=True, text=True,
            check=False, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return None
    return result.stdout.strip() or None


def fetch(url: str, attempts: int = 4) -> bytes:
    headers = {"User-Agent": "tanto-sync-ubo-scriptlets"}
    if url.startswith(API):
        authorization = token()
        if authorization:
            headers["Authorization"] = f"Bearer {authorization}"
    request = urllib.request.Request(url, headers=headers)
    for attempt in range(1, attempts + 1):
        try:
            with urllib.request.urlopen(request, timeout=300) as response:
                return response.read()
        except urllib.error.HTTPError as error:
            # A refusal is an answer; only a flaky response is worth retrying.
            if error.code < 500 or attempt == attempts:
                raise
            time.sleep(attempt)
        except urllib.error.URLError:
            if attempt == attempts:
                raise
            time.sleep(attempt)
    raise AssertionError("unreachable")


def fetch_json(url: str):
    return json.loads(fetch(url))


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def blob_id(data: bytes) -> str:
    """Git's own blob sha, so a local file can be compared to a tree entry."""
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def read_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        sys.exit(f"Missing manifest: {MANIFEST_PATH}. Run with --sync --ref <ref>.")
    return json.loads(MANIFEST_PATH.read_text())


def resolve_ref(ref: str) -> str:
    return fetch_json(f"{API}/repos/{REPOSITORY}/commits/{ref}")["sha"]


def list_upstream(ref: str) -> dict[str, dict[str, str]]:
    """Vendored path -> {upstream path, git blob sha}, from one tree listing.
    The vendored path is the upstream path: the modules import each other by
    relative path, so the layout is upstream's."""
    tree = fetch_json(f"{API}/repos/{REPOSITORY}/git/trees/{ref}?recursive=1")
    if tree.get("truncated"):
        sys.exit("GitHub truncated the tree listing; sync needs a narrower query.")

    files: dict[str, dict[str, str]] = {}
    for entry in tree["tree"]:
        if entry["type"] != "blob":
            continue
        path = entry["path"]
        directory, _, name = path.rpartition("/")
        wanted = path in VENDORED_FILES
        if directory in VENDORED_DIRECTORIES:
            suffix = VENDORED_DIRECTORIES[directory]
            wanted = suffix is None or name.endswith(suffix)
        if wanted:
            files[path] = {"upstream": path, "blob": entry["sha"]}

    missing = set(VENDORED_FILES) - set(files)
    if missing:
        sys.exit(f"Upstream no longer has: {', '.join(sorted(missing))}")
    return dict(sorted(files.items()))


def fetch_archive(commit: str, upstream_paths: set[str]) -> dict[str, bytes]:
    """Read the wanted files out of the commit's tarball — one request, and the
    contents are pinned to the commit rather than to a mutable branch."""
    archive = fetch(f"{CODELOAD}/{REPOSITORY}/tar.gz/{commit}")
    contents: dict[str, bytes] = {}
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tar:
        for member in tar:
            if not member.isfile():
                continue
            # Every path in a GitHub tarball is prefixed with <repo>-<commit>/.
            _, _, upstream_path = member.name.partition("/")
            if upstream_path in upstream_paths:
                handle = tar.extractfile(member)
                if handle is not None:
                    contents[upstream_path] = handle.read()
    return contents


def build_generated() -> list[dict[str, str]]:
    """Regenerate the descriptor files from the vendored copies and return
    their digests. Node reads each set by importing it, which is the only way
    to learn what registered itself."""
    generated = []
    for name, script in GENERATORS.items():
        result = subprocess.run(["node", str(SCRIPT_ROOT / script)], check=False)
        if result.returncode != 0:
            sys.exit(f"Could not build {name} from the vendored copies.")
        generated.append({"path": name, "sha256": digest((VENDOR_ROOT / name).read_bytes())})
    return generated


def verify(manifest: dict) -> int:
    """Fail when a vendored file was edited, lost, or is untracked."""
    problems: list[str] = []
    for vendored_path, expected in manifest["files"].items():
        path = VENDOR_ROOT / vendored_path
        if not path.exists():
            problems.append(f"missing: {vendored_path}")
        elif digest(path.read_bytes()) != expected["sha256"]:
            problems.append(f"edited locally: {vendored_path}")

    tracked = set(manifest["files"]) | set(GENERATORS)
    for path in sorted((VENDOR_ROOT / "src").rglob("*")):
        if path.is_file():
            relative = path.relative_to(VENDOR_ROOT).as_posix()
            if relative not in tracked:
                problems.append(f"not in the manifest: {relative}")

    for entry in manifest["generated"]:
        generated = VENDOR_ROOT / entry["path"]
        if not generated.exists():
            problems.append(f"missing: {entry['path']}")
        elif digest(generated.read_bytes()) != entry["sha256"]:
            problems.append(f"does not match its pin: {entry['path']}")

    if problems:
        print(f"Vendored uBO scriptlets do not match {MANIFEST_PATH.name}:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(
            "\nVendored files are copies and must not be edited. Re-run"
            "\nscripts/sync_ubo_scriptlets.py --sync to restore them.",
            file=sys.stderr,
        )
        return 1

    names = ", ".join(entry["path"] for entry in manifest["generated"])
    print(f"{len(manifest['files'])} vendored files and {names} match the "
          f"manifest ({manifest['ref'][:12]}).")
    return 0


def check_upstream(manifest: dict) -> int:
    head = resolve_ref(BRANCH)
    pinned = manifest["ref"]
    if head == pinned:
        print(f"Pinned at {BRANCH} head ({head[:12]}). Nothing to sync.")
        return 0

    upstream = list_upstream(head)
    tracked = manifest["files"]
    changes = sorted(
        [("added", path) for path in upstream if path not in tracked]
        + [("removed", path) for path in tracked if path not in upstream]
        + [("changed", path) for path, entry in upstream.items()
           if path in tracked and entry["blob"] != tracked[path]["blob"]]
    )

    print(f"Pinned:      {pinned[:12]}")
    print(f"{BRANCH} head: {head[:12]}")
    for kind, path in changes:
        print(f"  {kind}: {path}")
    if not changes:
        print("  no changes to the vendored files")
    print(f"\nCompare: https://github.com/{REPOSITORY}/compare/{pinned}...{head}")
    print(f"Sync with: scripts/sync_ubo_scriptlets.py --sync --ref {head}")
    return 0


def sync(ref: str, force: bool) -> int:
    manifest = read_manifest() if MANIFEST_PATH.exists() else {"files": {}}
    if not force and manifest["files"]:
        drifted = [
            path
            for path, entry in manifest["files"].items()
            if (VENDOR_ROOT / path).exists()
            and digest((VENDOR_ROOT / path).read_bytes()) != entry["sha256"]
        ]
        if drifted:
            print("Refusing to overwrite locally edited vendored files:", file=sys.stderr)
            for path in drifted:
                print(f"  {path}", file=sys.stderr)
            print("Re-run with --force to discard those edits.", file=sys.stderr)
            return 1

    commit = resolve_ref(ref)
    upstream = list_upstream(commit)
    contents = fetch_archive(commit, set(upstream))

    for existing in sorted((VENDOR_ROOT / "src").rglob("*")):
        if existing.is_file():
            existing.unlink()
    for vendored_path in VENDORED_FILES:
        (VENDOR_ROOT / vendored_path).unlink(missing_ok=True)

    files: dict[str, dict[str, str]] = {}
    for vendored_path, entry in upstream.items():
        data = contents.get(vendored_path)
        if data is None:
            sys.exit(f"{vendored_path} is missing from the {commit[:12]} archive")
        if blob_id(data) != entry["blob"]:
            sys.exit(f"{vendored_path} does not match its tree entry at {commit[:12]}")
        destination = VENDOR_ROOT / vendored_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
        files[vendored_path] = {"blob": entry["blob"], "sha256": digest(data)}
        print(f"  {vendored_path}")

    MANIFEST_PATH.write_text(
        json.dumps(
            {
                "repository": f"https://github.com/{REPOSITORY}",
                "branch": BRANCH,
                "ref": commit,
                "tag": ref if ref != commit and ref != BRANCH else None,
                "fetched": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                "license": "GPL-3.0-or-later",
                "generated": build_generated(),
                "files": files,
            },
            indent=2,
        )
        + "\n"
    )
    print(f"\nPinned {len(files)} files at {commit}.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--verify", action="store_true",
                     help="check the vendored tree against the manifest (no network)")
    mode.add_argument("--check-upstream", action="store_true",
                     help="report what changed upstream since the pin")
    mode.add_argument("--sync", action="store_true", help="re-fetch the vendored files")
    parser.add_argument("--ref", help="commit, tag, or branch to pin (default: the current pin)")
    parser.add_argument("--force", action="store_true",
                        help="overwrite vendored files that were edited locally")
    arguments = parser.parse_args()

    try:
        if arguments.verify:
            return verify(read_manifest())
        if arguments.check_upstream:
            return check_upstream(read_manifest())
        ref = arguments.ref or (read_manifest()["ref"] if MANIFEST_PATH.exists() else BRANCH)
        return sync(ref, arguments.force)
    except urllib.error.URLError as error:
        print(f"Could not reach GitHub: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
